apiVersion: management.loft.sh/v1
kind: Project
metadata:
  name: team-alpha
spec:
  displayName: team-alpha
  members:
    - kind: User
      name: admin
      clusterRole: project-admin
  allowedClusters:
    - name: "*"
  allowedTemplates:
    - kind: VirtualClusterTemplate
      name: "*"
