apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: my-vcluster
  namespace: p-my-project       # p- prefix + your project name
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  clusterRef:
    cluster: loft-cluster              # the connected cluster name
