apiVersion: management.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: dev-templatelqcb2
spec:
  displayName: dev-template
  versions:
    - version: "1.0.0"
      template:
        helmRelease:
          chart:
            version: "0.31.2"
          values: |
            sync:
              toHost:
                ingresses:
                  enabled: true
            controlPlane:
              coredns:
                enabled: true
                embedded: true
    - version: "1.1.0"
      template:
        helmRelease:
          chart:
            version: "0.32.0"
          values: |
            sync:
              toHost:
                ingresses:
                  enabled: true
            controlPlane:
              coredns:
                enabled: true
                embedded: true
